# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a base Node.js image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use a lightweight Node.js image for the production build
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --only=production

# Set the environment variable for the API key
ENV RIJKSMUSEUM_API_KEY=your-api-key-here

# Expose the necessary port (if required)
EXPOSE 3000

# Set the command to run the application
CMD ["node", "dist/index.js"]
